# ---------------------------LOCALHOST LINKS------------------------------------------------------
### Gets all from the contacts list
GET http://localhost:3000/contacts

### Gets one contact from contacts list
GET http://localhost:3000/contacts/696ad51c1268689c6f8be539

# ###
# GET http://localhost:3000/contacts/696ad5001268689c6f8be538

# ###
# GET http://localhost:3000/contacts/696ad51c1268689c6f8be539

### Posts in a new contact in contacts database
POST http://localhost:3000/contacts HTTP/1.1
content-type: application/json

{
    "firstName": "Katy",
	"lastName": "Luevano",
	"email": "katyluevano98@test.com",
	"favoriteColor": "Green",
	"birthday": "10/30/98"
}

### Updates a specific contact from contacts database
PUT http://localhost:3000/contacts/696ad51c1268689c6f8be539 HTTP/1.1
content-type: application/json

{
    "firstName": "Eber",
	"lastName": "Sanchez",
	"email": "eseSanchez94@test.com",
	"favoriteColor": "Grey purple",
	"birthday": "05/14/95"
}

### Deletes a specific contact from database
DELETE http://localhost:3000/contacts/6975a5bb7a1c7f139701d65c HTTP/1.1

# ------------------------------------RENDER LINKS-----------------------------------------------
### Gets all from the contacts list
GET https://tayde-luevano-cse341.onrender.com/contacts

###
GET https://tayde-luevano-cse341.onrender.com/contacts/696ad51c1268689c6f8be539

# ###
# GET https://tayde-luevano-cse341.onrender.com/contacts/696ad5001268689c6f8be538

# ###
# GET https://tayde-luevano-cse341.onrender.com/contacts/696ad51c1268689c6f8be539


### Posts in a new contact in contacts database
POST https://tayde-luevano-cse341.onrender.com/contacts HTTP/1.1
content-type: application/json

{
    "firstName": "Jacky",
	"lastName": "Jalati",
	"email": "jackyjalati@test.com",
	"favoriteColor": "Blue",
	"birthday": "02/11/96"
}

###
PUT https://tayde-luevano-cse341.onrender.com/contacts/696ad51c1268689c6f8be539 HTTP/1.1
content-type: application/json

{
    "firstName": "Eber",
	"lastName": "Sanchez",
	"email": "esanchez32@test.com",
	"favoriteColor": "Purple",
	"birthday": "05/20/95"
}

###
DELETE https://tayde-luevano-cse341.onrender.com/contacts/696ad5001268689c6f8be538 HTTP/1.1




